// <auto-generated />
using System;
using InterportCargo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterportCargo.Migrations
{
    [DbContext(typeof(InterportCargoDBContext))]
    [Migration("20251013135236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("InterportCargo.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("InterportCargo.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("InterportCargo.Models.Quotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerSize")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gst")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("QuotationId");

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("InterportCargo.Models.QuotationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageNature")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresFumigation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresQuarantine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("QuotationRequests", (string)null);
                });

            modelBuilder.Entity("InterportCargo.Models.RateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FortyFt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TwentyFt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RateItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeeType = "Wharf Booking fee",
                            FortyFt = 70m,
                            TwentyFt = 60m
                        },
                        new
                        {
                            Id = 2,
                            FeeType = "Lift on/Lift Off",
                            FortyFt = 120m,
                            TwentyFt = 80m
                        },
                        new
                        {
                            Id = 3,
                            FeeType = "Fumigation",
                            FortyFt = 280m,
                            TwentyFt = 220m
                        },
                        new
                        {
                            Id = 4,
                            FeeType = "LCL Delivery Depot",
                            FortyFt = 500m,
                            TwentyFt = 400m
                        },
                        new
                        {
                            Id = 5,
                            FeeType = "Tailgate Inspection",
                            FortyFt = 160m,
                            TwentyFt = 120m
                        },
                        new
                        {
                            Id = 6,
                            FeeType = "Storage Fee",
                            FortyFt = 300m,
                            TwentyFt = 240m
                        },
                        new
                        {
                            Id = 7,
                            FeeType = "Facility Fee",
                            FortyFt = 100m,
                            TwentyFt = 70m
                        },
                        new
                        {
                            Id = 8,
                            FeeType = "Wharf Inspection",
                            FortyFt = 90m,
                            TwentyFt = 60m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
